"""empty message

Revision ID: 28eefc611ffe
Revises: 
Create Date: 2025-03-28 11:03:08.210980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28eefc611ffe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laptops',
    sa.Column('laptop_id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=150), nullable=False),
    sa.Column('modelo', sa.String(length=150), nullable=False),
    sa.Column('pantalla', sa.String(length=150), nullable=False),
    sa.Column('procesador', sa.String(length=150), nullable=False),
    sa.Column('modelo_cpu', sa.String(length=150), nullable=False),
    sa.Column('sistema_operativo', sa.String(length=150), nullable=False),
    sa.Column('memoria_ram', sa.String(length=150), nullable=False),
    sa.Column('almacenamiento', sa.String(length=300), nullable=False),
    sa.Column('camara', sa.String(length=150), nullable=False),
    sa.Column('bateria', sa.String(length=150), nullable=False),
    sa.Column('precio', sa.String(length=50), nullable=False),
    sa.Column('tecnologia', sa.String(length=150), nullable=False),
    sa.Column('colores', sa.JSON(), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('imagen', sa.JSON(), nullable=False),
    sa.Column('funcion_especial', sa.String(length=300), nullable=False),
    sa.Column('descripcion_tarjeta_grafica', sa.String(length=300), nullable=False),
    sa.Column('tipo', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('laptop_id')
    )
    op.create_table('smartphones',
    sa.Column('smartphone_id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=150), nullable=False),
    sa.Column('pantalla', sa.String(length=150), nullable=False),
    sa.Column('procesador', sa.String(length=150), nullable=False),
    sa.Column('memoria_ram', sa.String(length=150), nullable=False),
    sa.Column('almacenamiento', sa.String(length=150), nullable=False),
    sa.Column('camara', sa.String(length=150), nullable=False),
    sa.Column('bateria', sa.String(length=150), nullable=False),
    sa.Column('precio', sa.String(length=50), nullable=False),
    sa.Column('conectividad', sa.String(length=150), nullable=False),
    sa.Column('colores', sa.JSON(), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('imagen', sa.JSON(), nullable=True),
    sa.Column('tipo', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('smartphone_id')
    )
    op.create_table('tv',
    sa.Column('tv_id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=150), nullable=False),
    sa.Column('contenido_de_la_caja', sa.String(length=150), nullable=False),
    sa.Column('modelo', sa.String(length=150), nullable=False),
    sa.Column('usos_recomendados', sa.String(length=150), nullable=False),
    sa.Column('año_modelo', sa.String(length=50), nullable=False),
    sa.Column('fabricante', sa.String(length=150), nullable=False),
    sa.Column('precio', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('pantalla', sa.String(length=150), nullable=False),
    sa.Column('conectividad', sa.String(length=150), nullable=False),
    sa.Column('medidas', sa.String(length=50), nullable=False),
    sa.Column('imagen', sa.JSON(), nullable=False),
    sa.Column('tipo', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('tv_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=75), nullable=True),
    sa.Column('email', sa.String(length=75), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('birthday_date', sa.String(length=15), nullable=True),
    sa.Column('user_image', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pedido',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('items', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('pedido_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido')
    op.drop_table('user')
    op.drop_table('tv')
    op.drop_table('smartphones')
    op.drop_table('laptops')
    # ### end Alembic commands ###
